spring:
  datasource:
    url: jdbc:postgresql://${pg-host}:${pg-port}/${pg-name}?currentSchema=${pg-schema}
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver
    password: ${pg-pass}
    username: ${pg-user}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 25
  application:
    name: user
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      serialization:
        fail-on-empty-beans: false
        indent_output: true
